id: P003298
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 10:53:32.898633
source_metadata:
  id: bdr:W28836
  title: རྟ་རྒྱུགས་ཁྲི་གསོལ
  author: ''
  volumes:
    a14712a4f1194b2086dc8d48e08be010:
      image_group_id: I4764
      title: ''
      volume_number: 1
      total_pages: 841
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
