id: IB420BD91
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:47:36+00:00'
last_modified: '2022-06-07T18:55:37.812132+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28836
  title: རྟ་རྒྱུགས་ཁྲི་གསོལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    73BF:
      image_group_id: I4764
      title: ''
      total_pages: 841
      order: 1
      base_file: 73BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
